#!/bin/bash
#SBATCH -o weather_result/weather_96.out
#SBATCH -J weather_96

model_name=delayformer

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./datasets/ \
  --data_path weather/weather.csv \
  --model_id weahter \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --lradj type1 \
  --e_layers 3 \
  --n_heads 12 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 7 \
  --batch_size 64 \
  --patience 5 \
  --train_epochs 10 \
  --d_model 128 \
  --des 'Exp' \
  --pe learnable_pe \
  --itr 1 \
  --n_vars 21 \
  --n 27 \
  --p1 5 \
  --p2 3

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./datasets/ \
  --data_path weather/weather.csv \
  --model_id weather_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --lradj type1 \
  --e_layers 3 \
  --n_heads 12 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 7 \
  --batch_size 128 \
  --patience 3 \
  --train_epochs 10 \
  --l2 0 \
  --d_model 128 \
  --des 'Exp' \
  --itr 1 \
  --pe learnable_pe \
  --n_vars 21 \
  --n 49 \
  --p1 6 \
  --p2 7
  
python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./datasets/ \
  --data_path weather/weather.csv \
  --model_id weather_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --lradj type1 \
  --e_layers 3 \
  --n_heads 12 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 7 \
  --batch_size 128 \
  --patience 3 \
  --train_epochs 10 \
  --l2 0 \
  --d_model 128 \
  --des 'Exp' \
  --itr 1 \
  --pe learnable_pe \
  --n_vars 21 \
  --n 49 \
  --p1 6 \
  --p2 7
  
python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./datasets/ \
  --data_path weather/weather.csv \
  --model_id weather_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --lradj type1 \
  --e_layers 3 \
  --n_heads 12 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 7 \
  --batch_size 128 \
  --patience 3 \
  --train_epochs 10 \
  --l2 0 \
  --d_model 128 \
  --des 'Exp' \
  --itr 1 \
  --pe learnable_pe \
  --n_vars 21 \
  --n 49 \
  --p1 6 \
  --p2 7
